### ISSUE TITLE
Create a release instead of pushing heavy files to master

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [GDGVIT/Selenium-Cookie-Injector#3]
### Issue Description
A tarball has been directly pushed [here](https://github.com/GDGVIT/Selenium-Cookie-Injector/tree/master/dist), and [chromedriver](https://github.com/GDGVIT/Selenium-Cookie-Injector/blob/master/chromedriver) has also been directly pushed to master. Occupying 9+ MB of space in the commit history.

### Todo

- [x] Remove the tarball from master
- [x] Create a release with the tarball
- [x] Add link to the release in the docs
- [x] Remove the chromedriver from master
- [x] Add a link to download the chromedriver

**Comment by aayushborkar14** [comment]
[This](https://github.com/c4milo/github-release) cli tool might be helpful to do it quickly...

**Comment by L04DB4L4NC3R** [comment]
> [This](https://github.com/c4milo/github-release) cli tool might be helpful to do it quickly...

Looks like a great tool. @D-E-F-E-A-T you can check it out for making the release.

**Comment by searchformyusername** [comment]
release means *pip install <name_v1>* right? It's already created. Will create a new version with changes now.

**Comment by searchformyusername** [comment]
Issues Resolved

**Comment by L04DB4L4NC3R** [comment]
No. A GitHub release, not a pip release.

**Comment by searchformyusername** [comment]
@L04DB4L4NC3R github release also made...
I clicked on releases and dragged the binary  over it.
is it something else?

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R github release also made...
> I clicked on releases and dragged the binary over it.
> is it something else?

Yup. Send a PR with the changes. See the checklist in this issue description to see what all the PR should require. After the PR is approved, I'll make another release in this repo.

**Comment by L04DB4L4NC3R** [comment]
Wait, just saw. Merged in #6 . Closing issue now

**Comment by searchformyusername** [comment]
@L04DB4L4NC3R ok

**Comment by L04DB4L4NC3R** [comment]
Solved in Pre-Alpha release [v1.0](https://github.com/GDGVIT/Selenium-Cookie-Injector/releases/tag/v1.0)
